name: publish

on:
    release:
        types: [published]

jobs:
    make_sdist:
        name: Make SDist and wheel
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                python-version: [3.8, 3.9, "3.10", 3.11, 3.12]
                os:
                  - ubuntu-latest
                  - windows-latest
                  - macos-latest
        steps:
        - uses: actions/checkout@v4

        - name: Install build
          run: pip install build

        - name: Build SDist
          run: python -m build --sdist

        - name: Build wheel
          run: python -m build wheel

        - uses: actions/upload-artifact@v3
          with:
            path: dist/*

    upload_on_pypi:
        needs: [make_sdist]
        environment: pypi
        permissions:
            id_token: write
        runs_on: ${{ matrix.os }}
        strategy:
            matrix:
                python-version: [3.8, 3.9, "3.10", 3.11, 3.12]
                os:
                  - ubuntu-latest
                  - windows-latest
                  - macos-latest
        steps:
            - uses: actions/download-artifact@v3
              with:
                name: artifact
                path: dist

            - uses: pypa/gh-action-pypi-publish@release/v1
              with:
                repository-url: https://pypi.org/legacy

    upload_on_conda:
        needs: [make_sdist]
        runs_on: ${{ matrix.os }}
        strategy:
            matrix:
                python-version: [3.8, 3.9, "3.10", 3.11, 3.12]
                os:
                  - ubuntu-latest
                  - windows-latest
                  - macos-latest
        steps:
            - uses: actions/checkout@v1
              with:
                environment-name: build-env
                create-args: >-
                  python=3.12
                  conda-build
                  anaconda-client

            - name: Build the recipe
              shell: bash -l {0}
              run: conda build recipes

            - name: upload on conda
              shell: bash -l {0}
              run: anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload --force /home/runner/
